### ISSUE TITLE
Get ReferenceError: toggle is not defined

### ISSUE THREAD

**Issue by mtabo** [phpfs/homebridge-http-switch#1]
Get this error when tray to add Homebridge to iDevice

/home/pi/homebridge-http-switch/index.js:36
				this.log('HTTP status failed for ' + toggle);
                                         ^
ReferenceError: toggle is not defined
    at HTTPSwitch.<anonymous> (/home/pi/homebridge-http-switch/index.js:36:42)
    at self.callback (/home/pi/homebridge-http-switch/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/home/pi/homebridge-http-switch/node_modules/request/request.js:877:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)

**Comment by phpfs** [comment]
Hi @mtabo,

this error happens due to a mistake on my side - feel free to submit a PR on that :)
The cause that I didn't come across this issue was that this part of the code gets only executed if the plugin fails to read the provided status URL and therefore doesn't know what to return to HomeKit.

Greetings,
phpfs
